### ISSUE TITLE
[Bug] Discover the node via its HOSTNAME is not very practical if the hostname differs from the k8s nodename.

### ISSUE THREAD

**Issue by Cellebyte** [telekom/das-schiff-network-operator#41]
## Description

Error from the operator log.
```log
github.com/telekom/das-schiff-network-operator/pkg/debounce.(*Debouncer).debounceRoutine
	/workspace/pkg/debounce/debounce.go:35
2023-08-28T09:27:48.495Z	ERROR	controller.vrfrouteconfiguration	error debouncing	{"reconciler group": "network.schiff.telekom.de", "reconciler kind": "VRFRouteConfiguration", "name": "bla", "namespace": "", "error": "Node \"customer-1-md-md-0-bb44bbb9fxzlnbj-lvpd9.site.location.example.com\" not found"}
```
```console
$ kubectl get nodes

NAME                                   STATUS   ROLES           AGE     VERSION
customer-1-7jnmh                           Ready    control-plane   2d20h   v1.25.12
customer-1-md-md-0-bb44bbb9fxzlnbj-6vkrl   Ready    worker          2d20h   v1.25.12
customer-1-md-md-0-bb44bbb9fxzlnbj-dxc5f   Ready    worker          2d19h   v1.25.12
customer-1-md-md-0-bb44bbb9fxzlnbj-lvpd9   Ready    worker          2d20h   v1.25.12
customer-1-w7k6b                           Ready    control-plane   2d20h   v1.25.12
customer-1-wk5dt                           Ready    control-plane   2d20h   v1.25.12

# login on the node
root@customer-1-md-md-0-bb44bbb9fxzlnbj-lvpd9:/# hostname
customer-1-md-md-0-bb44bbb9fxzlnbj-lvpd9.site.location.example.com
root@customer-1-md-md-0-bb44bbb9fxzlnbj-lvpd9:/# hostname --fqdn
customer-1-md-md-0-bb44bbb9fxzlnbj-lvpd9.site.location.example.com

root@customer-1-md-md-0-bb44bbb9fxzlnbj-lvpd9:/# hostnamectl status
   Static hostname: customer-1-md-md-0-bb44bbb9fxzlnbj-lvpd9.site.location.example.com
   Pretty hostname: localhost.local
         Icon name: computer-server
           Chassis: server
        Machine ID: cd9f27f0e96c4d74a3e4f37404cbc802
           Boot ID: b6139e6f644c4fa4a7a21d41cdbcfa22
  Operating System: Ubuntu 20.04.6 LTS
            Kernel: Linux 5.15.0-79-generic
      Architecture: x86-64

```

## Findings

Currently the operator discovers the node it is running on via the `HOSTNAME` environment variable.
This becomes problematic, when the hostname differs from the nodename in kubernetes.

Calico is using a spec field ref into their environment Variables called `NODENAME`.

## Suggestion
Use something like this in the deployment of network operators daemonset to ensure the environment variable is always correctly set for reconciliation loops.

```yaml
        - name: NODENAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
```

**Comment by schrej** [comment]
This will be added as part of #35. We'll just need to use it for this as well.

**Comment by schrej** [comment]
Considering it should only be a small change I'd say just add it to #35 to avoid more PRs that need to be rebased constantly.

**Comment by p-strusiewiczsurmacki-mobica** [comment]
Just pushed changes. Changed that [here](https://github.com/telekom/das-schiff-network-operator/blob/064ced652935f5cf7ce3ee79625f2ef7890f49d7/pkg/reconciler/layer2.go#L26) and [here](https://github.com/telekom/das-schiff-network-operator/blob/064ced652935f5cf7ce3ee79625f2ef7890f49d7/controllers/layer2networkconfiguration_controller.go#L77)

However I need to ask as I am not sure - should k8s node's name be also used in [frr package instead of os.Hostname() call?](https://github.com/telekom/das-schiff-network-operator/blob/064ced652935f5cf7ce3ee79625f2ef7890f49d7/pkg/frr/configure.go#L65)?

**Comment by Cellebyte** [comment]
> However I need to ask as I am not sure - should k8s node's name be also used in [frr package instead of os.Hostname() call?](https://github.com/telekom/das-schiff-network-operator/blob/064ced652935f5cf7ce3ee79625f2ef7890f49d7/pkg/frr/configure.go#L65)?

I think using the nodename env variable here would make it consistant.

**Comment by p-strusiewiczsurmacki-mobica** [comment]
@Cellebyte changed `os.Hostname()` to `os.Getenv()` to get the node name in `pkg/frr/configure.go`
