### ISSUE TITLE
[Bug] When someone configures two times the same prefix in a VrfRouteConfiguration FRR fails reloading.

### ISSUE THREAD

**Issue by Cellebyte** [telekom/das-schiff-network-operator#45]
## Description

Using `VrfRouteConfiguration` we do not check if the prefix is already in the list.
This can lead to the issue that the reload in frr is halted but we do not get feedback from network-operator that we did something wrong.

## Error

Configuration applied.

```yaml
apiVersion: network.schiff.telekom.de/v1alpha1
kind: VRFRouteConfiguration
metadata:
  name: vrf-name
spec:
  export: []
  import:
  - action: permit
    cidr: 10.0.140.0/22
  - action: permit
    cidr: 10.0.76.80/28
  - action: permit
    cidr: 10.0.76.0/22
  - action: permit
    cidr: 10.4.136.0/22
  - action: permit
    cidr: 10.0.140.0/22
  seq: 1
  vrf: vrf_name
```

Error received from FRR.
```log
Aug 29 16:23:30 customer-2-md-0-65f7878f59xpd6nb-zhbv5 frrinit.sh[16828]: The following commands were dynamically grouped into the same transaction and rejected:
Aug 29 16:23:30 customer-2-md-0-65f7878f59xpd6nb-zhbv5 frrinit.sh[16828]: - ip prefix-list pl_vrf_name_import_0 seq 1 permit 10.0.140.0/22
Aug 29 16:23:30 customer-2-md-0-65f7878f59xpd6nb-zhbv5 frrinit.sh[16828]: - ip prefix-list pl_vrf_name_import_0 seq 2 permit 10.0.76.80/28
Aug 29 16:23:30 customer-2-md-0-65f7878f59xpd6nb-zhbv5 frrinit.sh[16828]: - ip prefix-list pl_vrf_name_import_0 seq 3 permit 10.0.76.0/22
Aug 29 16:23:30 customer-2-md-0-65f7878f59xpd6nb-zhbv5 frrinit.sh[16828]: - ip prefix-list pl_vrf_name_import_0 seq 4 permit 10.4.136.0/22
Aug 29 16:23:30 customer-2-md-0-65f7878f59xpd6nb-zhbv5 frrinit.sh[16828]: - ip prefix-list pl_vrf_name_import_0 seq 5 permit 10.0.140.0/22
```

## Expectation

Either consolidating duplicated prefixes into the same prefix or raising an error in network-operator which advises the user to not define the same prefix twice.

**Comment by p-strusiewiczsurmacki-mobica** [comment]
Hi @Cellebyte, could you please give me a hint on when prefixes are considered to be duplicates?

In your example I can clearly see that there are 2 permit actions for `cidr: 10.0.140.0/22`. Now what if there will be opposing actions with same CIDR (1 `permit` and 1 `deny`)? Should we consider this an issue/duplicate? And what if the CIDR will be specified differently but will be in fact the same network? E.g:

```
- action: permit
    cidr: 10.0.76.8**0**/28
- action: permit
    cidr: 10.0.76.8**1**/28
```

**Comment by p-strusiewiczsurmacki-mobica** [comment]
Hi @Cellebyte 
Just created PR #47 on this. Tested with the examples you've provided and it it seems to work just fine. For duplicates list of duplicated items will be reported. For invalid CIDRs error will be returned and valid CIDR for network will be proposed.

Only first invalid CIDR will be reported for now. Should I test all the CIDRs and return a list as well?

```
patryk@xubuntu22:$ kubectl apply -f vrf-test/invalid/test1.yaml 
Error from server (there are duplicated items in the VrfRouteConfiguration: [10.0.140.0/22]): error when creating "vrf-test/invalid/test1.yaml": admission webhook "vvrfrouteconfiguration.kb.io" denied the request: there are duplicated items in the VrfRouteConfiguration: [10.0.140.0/22]

patryk@xubuntu22:$ kubectl apply -f vrf-test/invalid/test2.yaml 
Error from server (there are duplicated items in the VrfRouteConfiguration: [10.0.140.0/22]): error when creating "vrf-test/invalid/test2.yaml": admission webhook "vvrfrouteconfiguration.kb.io" denied the request: there are duplicated items in the VrfRouteConfiguration: [10.0.140.0/22]

patryk@xubuntu22:$ kubectl apply -f vrf-test/invalid/test3.yaml 
Error from server (error validating configuration item: CIDR 10.0.76.81/28 is invalid, CIDR for this network should be 10.0.76.80/28): error when creating "vrf-test/invalid/test3.yaml": admission webhook "vvrfrouteconfiguration.kb.io" denied the request: error validating configuration item: CIDR 10.0.76.81/28 is invalid, CIDR for this network should be 10.0.76.80/28
```

**Comment by Cellebyte** [comment]
Hey, so I just thought again about the sequence number.

I would need to verify the following case.

* sequence number increases in the `VRFRouteConfiguration` error regarding duplicate prefix still occurs or not.

```yaml
apiVersion: network.schiff.telekom.de/v1alpha1
kind: VRFRouteConfiguration
metadata:
  name: vrf-name-1
spec:
  export: []
  import:
  - action: deny
    cidr: 10.0.140.0/22
  seq: 1
  vrf: vrf_name
---
apiVersion: network.schiff.telekom.de/v1alpha1
kind: VRFRouteConfiguration
metadata:
  name: vrf-name-2
spec:
  export: []
  import:
  - action: permit
    cidr: 10.0.140.0/22
  seq: 2
  vrf: vrf_name
```
Depending on the outcome we would either need to factor in all `VRFRouteConfiguration`s for a `vrf: vrf_name` or we can stay at the current validation which checks inside one resource if we have a duplicate cidr.

**Comment by Cellebyte** [comment]
@chdxD1 small feedback regarding that edge case.

**Comment by Cellebyte** [comment]
Closed as it would be separate prefix list and should not collide with the other prefix-list.
The other check was already added in #47
