### ISSUE TITLE
[feature] ability to announce Services of type LoadBalancer

### ISSUE THREAD

**Issue by MaxRink** [telekom/das-schiff-network-operator#61]
As all current options don't work for our dual-stack use case we need a proper "speaker" for announcing Services of Type LoadBalancer.

What is out of scope: 
ExternalTrafficPolicy: Cluster, as there is no useful scenario for it in any site that we use NWOP
Limiting the amount of nodes that will publish an IP, as thats a non trivial task.

Building an controller that assigns IPs from Pools, we can reuse the MetalLB controller here
LoadBalancerClass: can be added later on.

* Assign IP from Pool to Service of Type LoadBalancer
  * IPRange
  * IPCIDR
* allow multiple Pools with different names
* Add BGP Multipath and ARP/ND support?
* Leak IP into correct VRF/VRFs
* Support metallb annotations and kube-vip annotations for backwards compatibility

What is in scope:
Announcing IPs on hosts that have Pods matching the selector in the service running on them.
The IPs should be picked up from the status field of the Service where the controller will have assigned them.
Throwing error event for unsupported modes (e.g. ExternalTrafficPolicy: Cluster)
Putting that into either a separate container or deployment to isolate issues from the normal NWOP
Must support DualStack Services

* Support only externalTrafficPolicy: Local
* Linux Table support which handles announcements from the status field.
* Handle [Serving Endpoint State](https://kubernetes.io/docs/concepts/services-networking/endpoint-slices/#serving)
* optionally add the possibility to configure the maximum announcements of a type: LoadBalancer Service to deal with potential ECMP overflow in bigger clusters.

**Comment by Cellebyte** [comment]
As we currently get changes into https://github.com/kube-vip/kube-vip I propose to not implement the functionality in network-operator unless we want l2 interfaces per loadbalancer ip or something similar which is not possible with kube-vip.

**Comment by Cellebyte** [comment]
@chdxD1 do you agree on closing this issue?

**Comment by chdxD1** [comment]
> @chdxD1 do you agree on closing this issue?

yes.
