### ISSUE TITLE
L2NwConf NodeSelector is case sensitive and doesn't support all operators

### ISSUE THREAD

**Issue by schrej** [telekom/das-schiff-network-operator#77]
The nodeSelector of Layer2NetworkConfigurations is case sensitive and the "matchExpressions" property doesn't support all current operators. This is due to the metav1.LabelSelectorToSelector helper function apparently being severely outdated (even though the doc comment instructs to keep it up to date, who would've thought!).

We should construct our own selector instead, probably similar to how metal3 is doing it: https://github.com/metal3-io/cluster-api-provider-metal3/blob/main/baremetal/metal3machine_manager.go#L807-L834

**Comment by p-strusiewiczsurmacki-mobica** [comment]
Issue addressed in #78
